### ISSUE TITLE
ConvertFrom-Json error message

### ISSUE THREAD

**Issue by daudphastar** [pbergo/qlik-saas-utils#2]
Hi,
Upon testing the **qlik_saas_delete_files** command using this command:

> qlik_saas_delete_files.ps1 -fileNames *.qvd -spaceName NewTestSpace

I run into this error message:
_> "Conversion from JSON failed with error: Unexpected character encountered while parsing value: U.Path '', line 0, position 0."_

PowerShell version: 7.3.6

**Comment by pbergo** [comment]
Hi @daudphastar 

I fixed code for qlik-cli version 2.22.13

Can you check again, please?

[],

Pedro

**Comment by daudphastar** [comment]
Hi @pbergo 
Tried upgrading qlik-cli version, but latest available from source is version 2.22.0 as of today.
Pasting in issue description, in case it helps.
```

Error: invalid argument "connectionId=\"$($dataconnection.id)\",top=100000" for "--query" flag: parse error on line 1, column 14: bare " in non-quoted-field
ConvertFrom-Json: C:\Users\UserName\.qlik\qlik_saas_delete_files.ps1:88
Line |
  88 |  … ctionId="$($dataconnection.id)",top=100000 | ConvertFrom-Json | Where …
     |                                                 ~~~~~~~~~~~~~~~~
     | Conversion from JSON failed with error: Unexpected character encountered while parsing value: U. Path '', line 0, position 0.
08/29/2023 09:54:12 [Info]: End of deleting files.
08/29/2023 09:54:12 [Info]: #################################################
```

**Comment by pbergo** [comment]
Hi again,

You´re right, the qlik-cli version is 2.22.0 (don´t know why I noted as 2.22.13!!)

To confirm, did you donwload new version from [qli_saas_delete_files.ps1](https://github.com/pbergo/qlik-saas-utils/blob/9ddb51b579343002d06137317ba383035129640d/qlik_saas_delete_files.ps1) also?

Can you provide following info, please?
- Powershell version ($PSVersionTAble.PSVersion)
- Command line

Tks,

**Comment by daudphastar** [comment]
Hi @pbergo,
Thanks for confirming. 
Powershell version: 7.3.6
Command line: Win Command Prompt. Microsoft Windows [Version 10.0.19045.3324]

```
PS C:\Users\UserName> qlik_saas_delete_files.ps1 -fileNames *.qvd -spaceName teststream -LogFile .\.qlik
08/30/2023 09:17:53 [Info]: #################################################
08/30/2023 09:17:53 [Info]: Starting deleting files from context [private.eu.qlikcloud.com]
08/30/2023 09:17:53 [Info]: Space parameter used is [teststream]
08/30/2023 09:17:53 [Info]: Files filter used is [*.qvd]
08/30/2023 09:17:53 [Info]: Confirm parameter used is [no]
08/30/2023 09:17:54 [Info]: Using space [teststream] ID [609b805c2be8840001a1b66e] !
08/30/2023 09:17:54 [Info]: Reading files from [teststream] ID [609b805c2be8840001a1b66e]... !
Error: invalid argument "connectionId=\"$($dataconnection.id)\",top=100000" for "--query" flag: parse error on line 1, column 14: bare " in non-quoted-field
ConvertFrom-Json: C:\Users\UserName\.qlik\qlik_saas_delete_files.ps1:88
Line |
  88 |  … ctionId="$($dataconnection.id)",top=100000 | ConvertFrom-Json | Where …
     |                                                 ~~~~~~~~~~~~~~~~
     | Conversion from JSON failed with error: Unexpected character encountered while parsing value: U. Path '', line 0, position 0.
08/30/2023 09:17:54 [Info]: End of deleting files.
08/30/2023 09:17:54 [Info]: #################################################
```

**Comment by pbergo** [comment]
Hi @Daud,

This issue happens for Powershell version 7.3.6. I tried to fix it but will take more time than I have today.

Can you download it to 7.2.13?

Follow the download link to windows: https://github.com/PowerShell/PowerShell/releases/tag/v7.2.13
[https://opengraph.githubassets.com/233d903e14f338c451cbac8f0ac78c01d680b8dc4222fcc83f8e408b95eb8507/PowerShell/PowerShell/releases/tag/v7.2.13]<https://github.com/PowerShell/PowerShell/releases/tag/v7.2.13>
Release v7.2.13 Release of PowerShell · PowerShell/PowerShell<https://github.com/PowerShell/PowerShell/releases/tag/v7.2.13>
7.2.13 - 2023-07-13 Tests Increase the timeout to make subsystem tests more reliable (#19937) Increase the timeout when waiting for the event log (#19936) Build and Packaging Improvements Bump ...
github.com

Please download the qlik_saas_delete_file.ps1 again because I fixed Log File naming generating.

Atc,

Pedro Bergo


________________________________
De: Daud Balling ***@***.***>
Enviado: quarta-feira, 30 de agosto de 2023 04:23
Para: pbergo/qlik-saas-utils ***@***.***>
Cc: Pedro Bergo ***@***.***>; Mention ***@***.***>
Assunto: Re: [pbergo/qlik-saas-utils] ConvertFrom-Json error message (Issue #2)


Hi @pbergo<https://github.com/pbergo>,
Thanks for confirming.
Powershell version: 7.3.6
Command line: Win Command Prompt. Microsoft Windows [Version 10.0.19045.3324]

PS C:\Users\UserName> qlik_saas_delete_files.ps1 -fileNames *.qvd -spaceName teststream -LogFile .\.qlik
08/30/2023 09:17:53 [Info]: #################################################
08/30/2023 09:17:53 [Info]: Starting deleting files from context [private.eu.qlikcloud.com]
08/30/2023 09:17:53 [Info]: Space parameter used is [teststream]
08/30/2023 09:17:53 [Info]: Files filter used is [*.qvd]
08/30/2023 09:17:53 [Info]: Confirm parameter used is [no]
08/30/2023 09:17:54 [Info]: Using space [teststream] ID [609b805c2be8840001a1b66e] !
08/30/2023 09:17:54 [Info]: Reading files from [teststream] ID [609b805c2be8840001a1b66e]... !
Error: invalid argument "connectionId=\"$($dataconnection.id)\",top=100000" for "--query" flag: parse error on line 1, column 14: bare " in non-quoted-field
ConvertFrom-Json: C:\Users\UserName\.qlik\qlik_saas_delete_files.ps1:88
Line |
  88 |  … ctionId="$($dataconnection.id)",top=100000 | ConvertFrom-Json | Where …
     |                                                 ~~~~~~~~~~~~~~~~
     | Conversion from JSON failed with error: Unexpected character encountered while parsing value: U. Path '', line 0, position 0.
08/30/2023 09:17:54 [Info]: End of deleting files.
08/30/2023 09:17:54 [Info]: #################################################

**Comment by daudphastar** [comment]
amazing - this works.

Downgrading PowerShell to 7.2.13 and using latest file versions solved the issue.

Thanks a lot!
